version: "3.8"

services:
  backend:
    build: .
    volumes:
      - ./app:/code/app
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - 5000:5000
    command: python app/main.py
